site_name: Synthea to Graph
nav:
  - Home: index.md
  - Mission: mission.md
  - Background: background.md
  - Clinical Graph Model: model.md
  - TigerGraph Loaders: tigergraph.md
  - Benchmarks: benchmarks.md
  - Contacts: contacts.md
repo_name: 'Go to GitHub'
repo_url: 'https://github.com/dmccreary/dmccreary'
# Standard mkdocs parameters from here down
# Replace all the markup after the repo_url line with this file
# This file was copied from 
edit_uri: 'blob/master/docs'
copyright: 'Copyright &copy; 2020 Optum'
theme:
  name: material
  feature:
    tabs: false
markdown_extensions:
  - admonition
  - pymdownx.details  
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences